CREATE OR REPLACE FUNCTION bm25_test()
RETURNS text
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE TABLE IF NOT EXISTS pg_bm25_words( word text NOT NULL, doc_id int, id integer, PRIMARY KEY(word,doc));
